export type PidInfo = { pid: string; name_en: string; name_ru: string; unit: string; kind: string; category: string };
export const PID_CATALOG: Record<string, PidInfo> = {
  "00": {
    pid: "00",
    name_en: "PIDs supported [01вЂ“20]",
    name_ru: "РџРѕРґРґРµСЂР¶РёРІР°РµРјС‹Рµ PID 01вЂ“20",
    unit: "mask",
    kind: "plain",
    category: "Support masks",
  },
  "20": {
    pid: "20",
    name_en: "PIDs supported [21вЂ“40]",
    name_ru: "РџРѕРґРґРµСЂР¶РёРІР°РµРјС‹Рµ PID 21вЂ“40",
    unit: "mask",
    kind: "plain",
    category: "Support masks",
  },
  "40": {
    pid: "40",
    name_en: "PIDs supported [41вЂ“60]",
    name_ru: "РџРѕРґРґРµСЂР¶РёРІР°РµРјС‹Рµ PID 41вЂ“60",
    unit: "mask",
    kind: "plain",
    category: "Support masks",
  },
  "60": {
    pid: "60",
    name_en: "PIDs supported [61вЂ“80]",
    name_ru: "РџРѕРґРґРµСЂР¶РёРІР°РµРјС‹Рµ PID 61вЂ“80",
    unit: "mask",
    kind: "plain",
    category: "Support masks",
  },
  "7F": {
    pid: "7F",
    name_en: "PIDs supported [81вЂ“A0]",
    name_ru: "РџРѕРґРґРµСЂР¶РёРІР°РµРјС‹Рµ PID 81вЂ“A0",
    unit: "mask",
    kind: "plain",
    category: "Support masks",
  },
  "80": {
    pid: "80",
    name_en: "Reserved/transition",
    name_ru: "Р РµР·РµСЂРІ/РїРµСЂРµС…РѕРґ",
    unit: "-",
    kind: "plain",
    category: "Other",
  },
  "01": {
    pid: "01",
    name_en: "Monitor status since DTCs cleared",
    name_ru: "РЎС‚Р°С‚СѓСЃ РјРѕРЅРёС‚РѕСЂРѕРІ РїРѕСЃР»Рµ РѕС‡РёСЃС‚РєРё DTC (MIL/РіРѕС‚РѕРІРЅРѕСЃС‚СЊ)",
    unit: "flags",
    kind: "plain",
    category: "Status / Diagnostic",
  },
  "02": {
    pid: "02",
    name_en: "Freeze DTC",
    name_ru: "Freeze DTC (РєРѕРґ Р·Р°РјРѕСЂРѕР¶РµРЅРЅРѕРіРѕ РєР°РґСЂР°)",
    unit: "code",
    kind: "plain",
    category: "Other",
  },
  "03": {
    pid: "03",
    name_en: "Fuel system status",
    name_ru: "РЎРѕСЃС‚РѕСЏРЅРёРµ С‚РѕРїР»РёРІРЅРѕР№ СЃРёСЃС‚РµРјС‹",
    unit: "status",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "04": {
    pid: "04",
    name_en: "Calculated engine load",
    name_ru: "Р Р°СЃС‡С‘С‚РЅР°СЏ РЅР°РіСЂСѓР·РєР° РґРІРёРіР°С‚РµР»СЏ",
    unit: "%",
    kind: "plain",
    category: "Engine",
  },
  "05": {
    pid: "05",
    name_en: "Engine coolant temperature",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РћР–",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "06": {
    pid: "06",
    name_en: "Short term fuel trim вЂ” Bank 1",
    name_ru: "РљСЂР°С‚РєРѕСЃСЂРѕС‡РЅР°СЏ РєРѕСЂСЂРµРєС†РёСЏ С‚РѕРїР»РёРІР° Р±Р°РЅРє 1 (STFT)",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "07": {
    pid: "07",
    name_en: "Long term fuel trim вЂ” Bank 1",
    name_ru: "Р”РѕР»РіРѕСЃСЂРѕС‡РЅР°СЏ РєРѕСЂСЂРµРєС†РёСЏ С‚РѕРїР»РёРІР° Р±Р°РЅРє 1 (LTFT)",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "08": {
    pid: "08",
    name_en: "Short term fuel trim вЂ” Bank 2",
    name_ru: "РљСЂР°С‚РєРѕСЃСЂРѕС‡РЅР°СЏ РєРѕСЂСЂРµРєС†РёСЏ С‚РѕРїР»РёРІР° Р±Р°РЅРє 2 (STFT)",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "09": {
    pid: "09",
    name_en: "Long term fuel trim вЂ” Bank 2",
    name_ru: "Р”РѕР»РіРѕСЃСЂРѕС‡РЅР°СЏ РєРѕСЂСЂРµРєС†РёСЏ С‚РѕРїР»РёРІР° Р±Р°РЅРє 2 (LTFT)",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "0A": {
    pid: "0A",
    name_en: "Fuel pressure (gauge)",
    name_ru: "Р”Р°РІР»РµРЅРёРµ С‚РѕРїР»РёРІР° (gauge)",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "0B": {
    pid: "0B",
    name_en: "Intake manifold absolute pressure (MAP)",
    name_ru: "MAP вЂ” Р°Р±СЃРѕР»СЋС‚РЅРѕРµ РґР°РІР»РµРЅРёРµ РІРѕ РІРїСѓСЃРєРµ",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "0C": {
    pid: "0C",
    name_en: "Engine RPM",
    name_ru: "РћР±РѕСЂРѕС‚С‹ РґРІРёРіР°С‚РµР»СЏ",
    unit: "rpm",
    kind: "plain",
    category: "Engine",
  },
  "0D": {
    pid: "0D",
    name_en: "Vehicle speed",
    name_ru: "РЎРєРѕСЂРѕСЃС‚СЊ Р°РІС‚РѕРјРѕР±РёР»СЏ",
    unit: "km/h",
    kind: "plain",
    category: "Vehicle",
  },
  "0E": {
    pid: "0E",
    name_en: "Timing advance",
    name_ru: "РћРїРµСЂРµР¶РµРЅРёРµ Р·Р°Р¶РёРіР°РЅРёСЏ",
    unit: "В°",
    kind: "plain",
    category: "Engine",
  },
  "0F": {
    pid: "0F",
    name_en: "Intake air temperature (IAT)",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РІРѕР·РґСѓС…Р° РЅР° РІРїСѓСЃРєРµ (IAT)",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "10": {
    pid: "10",
    name_en: "MAF air flow rate",
    name_ru: "MAF вЂ” РјР°СЃСЃРѕРІС‹Р№ СЂР°СЃС…РѕРґ РІРѕР·РґСѓС…Р°",
    unit: "g/s",
    kind: "plain",
    category: "Engine",
  },
  "11": {
    pid: "11",
    name_en: "Throttle position (absolute)",
    name_ru: "РџРѕР»РѕР¶РµРЅРёРµ РґСЂРѕСЃСЃРµР»СЏ (Р°Р±СЃРѕР»СЋС‚РЅРѕРµ)",
    unit: "%",
    kind: "plain",
    category: "Engine",
  },
  "12": {
    pid: "12",
    name_en: "Commanded secondary air status",
    name_ru: "РЎС‚Р°С‚СѓСЃ РІС‚РѕСЂРёС‡РЅРѕРіРѕ РІРѕР·РґСѓС…Р°",
    unit: "status",
    kind: "plain",
    category: "Status / Diagnostic",
  },
  "13": {
    pid: "13",
    name_en: "Oxygen sensors present (2 banks)",
    name_ru: "РќР°Р»РёС‡РёРµ O2 РґР°С‚С‡РёРєРѕРІ (2 Р±Р°РЅРєР°)",
    unit: "flags",
    kind: "plain",
    category: "Emissions",
  },
  "14": {
    pid: "14",
    name_en: "O2 Sensor 1 (B1S1) voltage / STFT",
    name_ru: "O2 B1S1 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "15": {
    pid: "15",
    name_en: "O2 Sensor 2 (B1S2) voltage / STFT",
    name_ru: "O2 B1S2 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "16": {
    pid: "16",
    name_en: "O2 Sensor 3 (B1S3) voltage / STFT",
    name_ru: "O2 B1S3 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "17": {
    pid: "17",
    name_en: "O2 Sensor 4 (B1S4) voltage / STFT",
    name_ru: "O2 B1S4 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "18": {
    pid: "18",
    name_en: "O2 Sensor 5 (B2S1) voltage / STFT",
    name_ru: "O2 B2S1 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "19": {
    pid: "19",
    name_en: "O2 Sensor 6 (B2S2) voltage / STFT",
    name_ru: "O2 B2S2 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "1A": {
    pid: "1A",
    name_en: "O2 Sensor 7 (B2S3) voltage / STFT",
    name_ru: "O2 B2S3 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "1B": {
    pid: "1B",
    name_en: "O2 Sensor 8 (B2S4) voltage / STFT",
    name_ru: "O2 B2S4 (РЅР°РїСЂСЏР¶РµРЅРёРµ/РєРѕСЂСЂРµРєС†РёСЏ)",
    unit: "mixed",
    kind: "plain",
    category: "Electrical",
  },
  "1C": {
    pid: "1C",
    name_en: "OBD standards this vehicle conforms to",
    name_ru: "РЎС‚Р°РЅРґР°СЂС‚ OBD Р°РІС‚РѕРјРѕР±РёР»СЏ",
    unit: "enum",
    kind: "plain",
    category: "Other",
  },
  "1D": {
    pid: "1D",
    name_en: "Oxygen sensors present (4 banks)",
    name_ru: "РќР°Р»РёС‡РёРµ O2 РґР°С‚С‡РёРєРѕРІ (4 Р±Р°РЅРєР°)",
    unit: "flags",
    kind: "plain",
    category: "Emissions",
  },
  "1E": {
    pid: "1E",
    name_en: "Auxiliary input status",
    name_ru: "РЎС‚Р°С‚СѓСЃ РґРѕРї. РІС…РѕРґР°",
    unit: "flags",
    kind: "plain",
    category: "Status / Diagnostic",
  },
  "1F": {
    pid: "1F",
    name_en: "Run time since engine start",
    name_ru: "Р’СЂРµРјСЏ СЂР°Р±РѕС‚С‹ РїРѕСЃР»Рµ Р·Р°РїСѓСЃРєР°",
    unit: "s",
    kind: "plain",
    category: "Engine",
  },
  "21": {
    pid: "21",
    name_en: "Distance traveled with MIL on",
    name_ru: "РџСЂРѕР±РµРі СЃ MIL (Check Engine)",
    unit: "km",
    kind: "plain",
    category: "Other",
  },
  "22": {
    pid: "22",
    name_en: "Fuel rail pressure (relative to vacuum)",
    name_ru: "Р”Р°РІР»РµРЅРёРµ РІ С‚РѕРїР»РёРІРЅРѕР№ СЂРµР№РєРµ (РѕС‚РЅ. Рє СЂР°Р·СЂРµР¶РµРЅРёСЋ)",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "23": {
    pid: "23",
    name_en: "Fuel rail pressure (diesel/direct injection)",
    name_ru: "Р”Р°РІР»РµРЅРёРµ РІ С‚РѕРїР»РёРІРЅРѕР№ СЂРµР№РєРµ (DI/РґРёР·РµР»СЊ)",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "2C": {
    pid: "2C",
    name_en: "Commanded EGR",
    name_ru: "РљРѕРјР°РЅРґР° EGR",
    unit: "%",
    kind: "plain",
    category: "Emissions",
  },
  "2D": {
    pid: "2D",
    name_en: "EGR error",
    name_ru: "РћС€РёР±РєР° EGR",
    unit: "%",
    kind: "plain",
    category: "Emissions",
  },
  "2E": {
    pid: "2E",
    name_en: "Commanded evaporative purge",
    name_ru: "РљРѕРјР°РЅРґР° РїСЂРѕРґСѓРІРєРё EVAP",
    unit: "%",
    kind: "plain",
    category: "Emissions",
  },
  "2F": {
    pid: "2F",
    name_en: "Fuel level input",
    name_ru: "РЈСЂРѕРІРµРЅСЊ С‚РѕРїР»РёРІР°",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "30": {
    pid: "30",
    name_en: "Warm-ups since codes cleared",
    name_ru: "РџСЂРѕРіСЂРµРІС‹ РїРѕСЃР»Рµ СЃР±СЂРѕСЃР° DTC",
    unit: "count",
    kind: "plain",
    category: "Other",
  },
  "31": {
    pid: "31",
    name_en: "Distance since codes cleared",
    name_ru: "РџСЂРѕР±РµРі РїРѕСЃР»Рµ СЃР±СЂРѕСЃР° DTC",
    unit: "km",
    kind: "plain",
    category: "Other",
  },
  "32": {
    pid: "32",
    name_en: "Evap system vapor pressure",
    name_ru: "Р”Р°РІР»РµРЅРёРµ РїР°СЂРѕРІ EVAP",
    unit: "Pa",
    kind: "plain",
    category: "Pressures",
  },
  "33": {
    pid: "33",
    name_en: "Absolute barometric pressure (BARO)",
    name_ru: "BARO вЂ” Р°С‚РјРѕСЃС„РµСЂРЅРѕРµ РґР°РІР»РµРЅРёРµ",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "3C": {
    pid: "3C",
    name_en: "Catalyst temperature Bank1 Sensor1",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РєР°С‚Р°Р»РёР·Р°С‚РѕСЂР° B1S1",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "3D": {
    pid: "3D",
    name_en: "Catalyst temperature Bank2 Sensor1",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РєР°С‚Р°Р»РёР·Р°С‚РѕСЂР° B2S1",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "3E": {
    pid: "3E",
    name_en: "Catalyst temperature Bank1 Sensor2",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РєР°С‚Р°Р»РёР·Р°С‚РѕСЂР° B1S2",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "3F": {
    pid: "3F",
    name_en: "Catalyst temperature Bank2 Sensor2",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РєР°С‚Р°Р»РёР·Р°С‚РѕСЂР° B2S2",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "41": {
    pid: "41",
    name_en: "Monitor status this drive cycle",
    name_ru: "РЎС‚Р°С‚СѓСЃ РјРѕРЅРёС‚РѕСЂРѕРІ С‚РµРєСѓС‰РµРіРѕ С†РёРєР»Р°",
    unit: "flags",
    kind: "plain",
    category: "Status / Diagnostic",
  },
  "42": {
    pid: "42",
    name_en: "Control module voltage",
    name_ru: "РќР°РїСЂСЏР¶РµРЅРёРµ РїРёС‚Р°РЅРёСЏ Р­Р‘РЈ",
    unit: "V",
    kind: "plain",
    category: "Electrical",
  },
  "43": {
    pid: "43",
    name_en: "Absolute load value",
    name_ru: "РђР±СЃРѕР»СЋС‚РЅР°СЏ РЅР°РіСЂСѓР·РєР°",
    unit: "%",
    kind: "plain",
    category: "Other",
  },
  "44": {
    pid: "44",
    name_en: "Commanded air-fuel equivalence ratio",
    name_ru: "РљРѕРјР°РЅРґСѓРµРјР°СЏ Р»СЏРјР±РґР° (СЌРєРІ. AFR)",
    unit: "ratio",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "45": {
    pid: "45",
    name_en: "Relative throttle position",
    name_ru: "РћС‚РЅРѕСЃРёС‚РµР»СЊРЅРѕРµ РїРѕР»РѕР¶РµРЅРёРµ РґСЂРѕСЃСЃРµР»СЏ",
    unit: "%",
    kind: "plain",
    category: "Engine",
  },
  "46": {
    pid: "46",
    name_en: "Ambient air temperature",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РѕРєСЂСѓР¶Р°СЋС‰РµРіРѕ РІРѕР·РґСѓС…Р°",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "49": {
    pid: "49",
    name_en: "Accelerator pedal position D",
    name_ru: "РџРµРґР°Р»СЊ РіР°Р·Р° D",
    unit: "%",
    kind: "plain",
    category: "Other",
  },
  "4A": {
    pid: "4A",
    name_en: "Accelerator pedal position E",
    name_ru: "РџРµРґР°Р»СЊ РіР°Р·Р° E",
    unit: "%",
    kind: "plain",
    category: "Other",
  },
  "4B": {
    pid: "4B",
    name_en: "Accelerator pedal position F",
    name_ru: "РџРµРґР°Р»СЊ РіР°Р·Р° F",
    unit: "%",
    kind: "plain",
    category: "Other",
  },
  "4C": {
    pid: "4C",
    name_en: "Commanded throttle actuator",
    name_ru: "РљРѕРјР°РЅРґР° РїСЂРёРІРѕРґР° РґСЂРѕСЃСЃРµР»СЏ",
    unit: "%",
    kind: "plain",
    category: "Engine",
  },
  "4D": {
    pid: "4D",
    name_en: "Time run with MIL on",
    name_ru: "Р’СЂРµРјСЏ СЂР°Р±РѕС‚С‹ СЃ MIL",
    unit: "min",
    kind: "plain",
    category: "Other",
  },
  "4E": {
    pid: "4E",
    name_en: "Time since codes cleared",
    name_ru: "Р’СЂРµРјСЏ СЃ РјРѕРјРµРЅС‚Р° СЃР±СЂРѕСЃР° DTC",
    unit: "min",
    kind: "plain",
    category: "Other",
  },
  "51": {
    pid: "51",
    name_en: "Fuel type",
    name_ru: "РўРёРї С‚РѕРїР»РёРІР°",
    unit: "enum",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "52": {
    pid: "52",
    name_en: "Ethanol fuel %",
    name_ru: "РџСЂРѕС†РµРЅС‚ СЌС‚Р°РЅРѕР»Р°",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "53": {
    pid: "53",
    name_en: "Absolute evap system vapor pressure",
    name_ru: "РђР±СЃРѕР»СЋС‚РЅРѕРµ РґР°РІР»РµРЅРёРµ РїР°СЂРѕРІ EVAP",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "59": {
    pid: "59",
    name_en: "Fuel rail absolute pressure",
    name_ru: "Р”Р°РІР»РµРЅРёРµ РІ СЂРµР№РєРµ (Р°Р±СЃРѕР»СЋС‚РЅРѕРµ)",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "5C": {
    pid: "5C",
    name_en: "Engine oil temperature",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РјР°СЃР»Р° РґРІРёРіР°С‚РµР»СЏ",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "5E": {
    pid: "5E",
    name_en: "Engine fuel rate",
    name_ru: "Р Р°СЃС…РѕРґ С‚РѕРїР»РёРІР° РґРІРёРіР°С‚РµР»СЏ",
    unit: "L/h",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "61": {
    pid: "61",
    name_en: "DriverвЂ™s demand engine torque",
    name_ru: "Р—Р°РїСЂРѕСЃ РІРѕРґРёС‚РµР»СЏ РїРѕ РјРѕРјРµРЅС‚Сѓ",
    unit: "%",
    kind: "plain",
    category: "Engine",
  },
  "62": {
    pid: "62",
    name_en: "Actual engine torque",
    name_ru: "Р¤Р°РєС‚РёС‡РµСЃРєРёР№ РјРѕРјРµРЅС‚ РґРІРёРіР°С‚РµР»СЏ",
    unit: "%",
    kind: "plain",
    category: "Engine",
  },
  "63": {
    pid: "63",
    name_en: "Engine reference torque",
    name_ru: "Р­С‚Р°Р»РѕРЅРЅС‹Р№ РјРѕРјРµРЅС‚ РґРІРёРіР°С‚РµР»СЏ",
    unit: "Nm",
    kind: "plain",
    category: "Engine",
  },
  "6F": {
    pid: "6F",
    name_en: "Turbo compressor inlet pressure",
    name_ru: "Р”Р°РІР»РµРЅРёРµ РЅР° РІС…РѕРґРµ РєРѕРјРїСЂРµСЃСЃРѕСЂР° С‚СѓСЂР±РёРЅС‹",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "73": {
    pid: "73",
    name_en: "Exhaust pressure",
    name_ru: "Р”Р°РІР»РµРЅРёРµ РІС‹С…Р»РѕРїР°",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "74": {
    pid: "74",
    name_en: "Turbocharger RPM",
    name_ru: "РћР±РѕСЂРѕС‚С‹ С‚СѓСЂР±РёРЅС‹",
    unit: "rpm",
    kind: "plain",
    category: "Engine",
  },
  "77": {
    pid: "77",
    name_en: "Charge air cooler temperature",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РїРѕСЃР»Рµ РёРЅС‚РµСЂРєСѓР»РµСЂР° (CAC)",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "78": {
    pid: "78",
    name_en: "Exhaust gas temperature bank 1",
    name_ru: "EGT Р±Р°РЅРє 1",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "79": {
    pid: "79",
    name_en: "Exhaust gas temperature bank 2",
    name_ru: "EGT Р±Р°РЅРє 2",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "84": {
    pid: "84",
    name_en: "Manifold surface temperature",
    name_ru: "РўРµРјРїРµСЂР°С‚СѓСЂР° РїРѕРІРµСЂС…РЅРѕСЃС‚Рё РІРїСѓСЃРєР°",
    unit: "В°C",
    kind: "plain",
    category: "Temperatures",
  },
  "87": {
    pid: "87",
    name_en: "Intake manifold absolute pressure (extended)",
    name_ru: "MAP (СЂР°СЃС€РёСЂ.)",
    unit: "kPa",
    kind: "pressure",
    category: "Pressures",
  },
  "90": {
    pid: "90",
    name_en: "Engine exhaust flow rate",
    name_ru: "Р Р°СЃС…РѕРґ РІС‹С…Р»РѕРїР° РґРІРёРіР°С‚РµР»СЏ",
    unit: "g/s",
    kind: "plain",
    category: "Engine",
  },
  "91": {
    pid: "91",
    name_en: "Fuel system percentage use",
    name_ru: "РџСЂРѕС†РµРЅС‚ РёСЃРїРѕР»СЊР·РѕРІР°РЅРёСЏ СЂРµР¶РёРјРѕРІ С‚РѕРїР»РёРІР°",
    unit: "%",
    kind: "plain",
    category: "Fuel / AFR",
  },
  "94": {
    pid: "94",
    name_en: "Transmission actual gear",
    name_ru: "РўРµРєСѓС‰Р°СЏ РїРµСЂРµРґР°С‡Р°",
    unit: "gear",
    kind: "plain",
    category: "Transmission",
  },
  "96": {
    pid: "96",
    name_en: "Odometer (if provided)",
    name_ru: "РћРґРѕРјРµС‚СЂ (РµСЃР»Рё РѕС‚РґР°С‘С‚ Р­Р‘РЈ)",
    unit: "km",
    kind: "plain",
    category: "Vehicle",
  },
};


